### ISSUE TITLE
Issue when evaluating component for use case

### ISSUE THREAD

**Issue by mouhb** [RISCOSS/riscoss-wiki-ui#4] opened 2015-03-27 09:44 UTC
![unnamed](https://cloud.githubusercontent.com/assets/3015046/6865445/273ae58a-d46e-11e4-9243-c53253a4dc90.png)

**Comment by cjdelisle** [comment] 2015-03-31 10:15
This would be more useful with the content of the RAWOUT (which goes off the screen)

**Comment by cjdelisle** [comment] 2015-04-03 10:22
Looks like a dupe of https://github.com/RISCOSS/riscoss-platform-core/issues/19

**Closed by cjdelisle** 2015-04-03 10:22 UTC
